### PR TITLE
fix(urls): update 4xx error pages preview, to accept exceptions

### LINKED ISSUE #444: Error pages need an exception parameter on django 1.9
The test exception pages are no longer working on django 1.9.

Affected pages:

- 400
- 403
- 404

Traceback (404):
```
File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/usr/local/lib/python3.5/contextlib.py" in inner
  30.                 return func(*args, **kwds)

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

Exception Type: TypeError at /404/
Exception Value: page_not_found() missing 1 required positional argument: 'exception'
```

### PR DESCRIPTION
**Pull request by theskumar**
closes #444

### CODE REVIEW

**Comment by jayfk** [comment]
LGTM
